[update]
tasks = ["code", "normalize"]

[update.code]
codePath = "../AxeSync/"
localizablePath = "../AxeSync/"
defaultToKeys = true
additive = false
unstripped = false
customFunction = "DSLocalizedString"

[update.normalize]
path = "."
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
