target 'AxeSync_Example' do
  platform :ios, '10.0'
  
  pod 'AxeSync', :path => '../'
  pod 'KVO-MVVM', '0.5.1'
  pod 'ios-app', :git => 'https://github.com/axerunners/ios-app.git', :branch => 'master', :commit => 'a79e671e11b09c0610224130bc58547da9bbd38d'

  target 'AxeSync_Tests' do
    inherit! :search_paths
  end
end

# fixes warnings about unsupported Deployment Target in Xcode 10
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'AFNetworking'
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
